spring.application.name=api-gateway

# Server Port configuration
server.port = 8765

# eureka config
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka

#discovery locator config
spring.cloud.gateway.discovery.locator.enabled = true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId = true